name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.4'
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby
      uses: ruby/setup-ruby@ae195bbe749a7cef685ac729197124a48305c1cb # v1.276.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
    - name: Run tests
      run: bundle exec rake
